name: Update Copyright Year

on:
  schedule:
    - cron: '0 0 1 1 *' # run on the first day of every year

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Update Update Copyright Year
        run: |
          # Add your script here to modify the README file
          # For example, you can use sed to replace a specific string
          YEAR=$(date +%Y)
          README_FILE=".github/Profile/README.md"
          OLD_TEXT="Copyright 2022 [RepoMonitor]"
          NEW_TEXT="Copyright 2022 - $YEAR [RepoMonitor]"
          
          sed -i "s/$OLD_TEXT/$NEW_TEXT/g" "$README_FILE"
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update README for the new year'
